language: java
sudo: false
dist: trusty
install: true

addons:
    firefox: latest
    apt:
        packages:
            - google-chrome-stable
    sonarcloud:
        organization: "bonigarcia-github"
        token:
            secure: "POzNlNrg9SiIm2iI+OObyxl76yA3hjZ5k8F3+dNhjSWsSX+fE+QyVVZ6ySai952XNO9S54C370OhLey5KwddPZPpPfTUBWL9Puv6b6N9o8DmBZ8SJGrlZ67GySjdB9CJS4ZM8Yto+YIS+OmFm9drAU0RSQ3WKztsXZLYKSFJZUac7H/DM8fh4uBFo2jBKOSJ/62c3jljNjAYhl/dkHU3pZu1JXwgfiULjBxKkPct2hPOFr1ho447Ui4M3ypH290yVIX1x/vmQcbU/ap603LOIoW4oUj/7hYxJNCCvm6gkO5VerPUOVOjLZYZznIy4dOjNgX/Q/Dct06wNI/VM3aOvBf+0jAzJ/oQgziABtB8LDkYfvVgE4IJShyeNPASKztvuf/g8P9HcDn350Ea73uwkcmbNZ/MWCHFE6Ahpor/nw9Z5N0U+djfelsKsBSONK5yKp27o96qxyz1lfNqquL3qkakQM0zmYNO8F0Zwc/hRse6wtVRW4BPE4tgSaDSgSbt/mrKQwDPZXa87ne9FtOCiVVYWviXQApA7CWxXXgd0ITlmrLfJvllXebc0BXAFQaa1Ct1b65B3Ox6edlh4sBcjfaY1d61cnKk0nFVVupb3bbSG3V1yfOPEBnfQeEUxmjKrbOfjVaN5qCPRZmHih34FS9TFNSFuvebFbXNzkr5Z3U="

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start &
    - sleep 3

script:
    - mvn test sonar:sonar
    - bash <(curl -s https://codecov.io/bash)
